name: Unzip and Deploy to Vercel

on:
  push:
    branches: [ "main" ]
    paths:
      - "*.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Extract Zip
        run: |
          rm -rf public
          mkdir public
          unzip -o *.zip -d public

      - name: Commit Extracted Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Extract zip and update public"
          git push
